version: '3.1'
services: 
  node:
    container_name: node-refresh
    restart: always
    build: .
    ports: 
      - '80:3000'
    links:
      - mongodb
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
